1) Initialize an empty array with size 2X2.

In [12]:
import numpy as np

emptyArray = np.empty((2,2));
print(emptyArray);


[[5.05887e-310 0.00000e+000]
 [1.58101e-322 0.00000e+000]]


2)  Initialize an all one array with size 4X2.

In [13]:
import numpy as np

oneArray = np.ones((4,2));
print(oneArray);

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3)Return a new array of given shape and type, filled with fill_value.{Hint: np.full}


In [16]:
import numpy as np

newArray = np.full((4,2),fill_value=1);
print (newArray);


[[1 1]
 [1 1]
 [1 1]
 [1 1]]


4) Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [17]:
import numpy as np

newArray = np.zeros((4,2));
print(newArray);


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


5) Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [18]:
import numpy as np

newArray = np.ones((4,2));
print (newArray);


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


6) For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [19]:
import numpy as np

new_list = [1,2,3,4];
array= np.array(new_list);
print(array);

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1) Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [21]:
import numpy as np

array = np.arange(10,50);
print (array);


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2) Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [25]:
import numpy as np

array = np.arange(0,9);
reshapeArray = array.reshape(3,3);
print (reshapeArray);

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3) Create a 3X3 identity matrix.{Hint:np.eye()}

In [29]:
import numpy as np

array= np.eye(3,3);
print (array);

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4) Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [33]:
import numpy as np

array = np.random.random(30);
meanOfArray = np.mean(array);

print("The mean of the random array is: ",meanOfArray);

The mean of the random array is:  0.5822711182200723


5) Create a 10X10 array with random values and find the minimum and maximum values.

In [44]:
import numpy as np

array = np.random.rand(10,10);
minimum = np.min(array);
maximum = np.max(array);

print ("minimum: ", minimum, "maximum: ", maximum);

minimum:  0.0014924729389804714 maximum:  0.9932275438625203


6) Create a zero array of size 10 and replace 5th element with 1.

In [38]:
import numpy as np

array = np.zeros(10);
array[4]= 1;
print (array);

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7) Reverse an array arr = [1,2,0,0,4,0].

In [45]:
import numpy as np

arr= [1,2,0,0,4,0];
reversal = arr[:: -1];
print(reversal);

[0, 4, 0, 0, 2, 1]


8) Create a 2d array with 1 on border and 0 inside.

In [53]:
import numpy as np

array = np.ones((10,10));
array[ 1:-1, 1:-1]=0;
print(array);

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


9) Create a 8X8 matrix and fill it with a checkerboard pattern.

In [57]:
import numpy as np

matrix = np.zeros((8,8));
matrix[::2, ::2]=1;
matrix[1::2, 1::2]=1;
print(matrix);

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Problem - 3: Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

1) Add the two array.

In [60]:
import numpy as np

x= np.array([[1,2],[3,5]]);

y= np.array([[5,6],[7,8]]);

add = np.add(x,y);

print("The total sum is: ", add);


The total sum is:  [[ 6  8]
 [10 13]]


2) Subtract the two array.

In [62]:
import numpy as np

x= np.array([[1,2],[3,5]]);

y= np.array([[5,6],[7,8]]);

subtract = np.subtract(y,x);

print("Subtracting x from y gives us: ", subtract);

Subtracting x from y gives us:  [[4 4]
 [4 3]]


3) Multiply the array with any integers of your choice.

In [64]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

xMultiplication = 4*x;
print (xMultiplication);

yMultiplication = 7*y;
print (yMultiplication);

vMultiplication = 3*v;
print (vMultiplication);

wMultiplication = 10*w;
print (wMultiplication);

[[ 4  8]
 [12 20]]
[[35 42]
 [49 56]]
[27 30]
[110 120]


4) Find the square of each element of the array.

In [66]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

squareX = np.square(x);

squarey = np.square(y);

squarev = np.square(v);

squarew = np.square(w);

print(squareX);
print(squarey);
print(squarev);
print(squarew);


[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


5) Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [69]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dotProductOne = np.dot(v,w);
print(dotProductOne);

dotProductTwo = np.dot(x,v);
print(dotProductTwo);

dotProductThree = np.dot(x,y);
print(dotProductThree);

219
[29 77]
[[19 22]
 [50 58]]


6) Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [78]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concatenate_xy = np.concatenate((x,y), axis= 1);
print(concatenate_xy);

concatenate_vw= np.vstack((v,w)).T;
print(concatenate_vw);

[[1 2 5 6]
 [3 5 7 8]]
[[ 9 11]
 [10 12]]


7) Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [79]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

concatenate= np.concatenate((x,v),0);
print(concatenate);

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The arrays we are trying to concatenate must have same numbers of dimensions, that's why its showing an error.

Problem - 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

1) Prove A.A−1 = I.

In [80]:
import numpy as np

A = np.array([[3,4],[7,8]])
A_inverse= np.linalg.inv(A);

dotProduct= np.dot(A,A_inverse);
print(dotProduct);


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2) Prove AB ̸= BA.

In [81]:
import numpy as np

A = np.array([[3, 4], [7, 8]]);
B = np.array([[5, 3], [2, 1]]);

A_B = np.dot(A, B);
B_A = np.dot(B, A);

print(A_B);
print(B_A);

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


3) Prove (AB)

T = BTAT

In [82]:
import numpy as np

A = np.array([[3, 4], [7, 8]]);
B = np.array([[5, 3], [2, 1]]);


AB_T = np.transpose(np.dot(A, B));


BT_AT = np.dot(np.transpose(B), np.transpose(A));

print(AB_T);
print(BT_AT);

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [83]:
import numpy as np

A= np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]]);
B = np.array([-1, -3, 9]);

A_inverse = np.linalg.inv(A);
X= np.dot(A_inverse, B);
print(X);

[ 2.  1. -2.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [84]:
import numpy as np

A= np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]]);
B = np.array([-1, -3, 9]);

A_inverse = np.linalg.inv(A);
X= np.dot(A_inverse, B);
print(X);

[ 2.  1. -2.]


Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [87]:
import time


A = [i for i in range(1, 1000001)]
B = [i for i in range(1, 1000001)]


start = time.time()


addition = [A[i] + B[i] for i in range(len(A))]

end = time.time()

print(f"Time taken: {end - start}")



Time taken: 0.3209805488586426


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [88]:
import numpy as np
import time

A = np.arange(1, 1000001)
B = np.arange(1, 1000001)

start = time.time()

addition = A + B

end = time.time()

print(f"Time taken: {end - start}")



Time taken: 0.0041425228118896484


Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

In [89]:
import time

A = [i for i in range(1, 1000001)]
B = [i for i in range(1, 1000001)]

start = time.time()

multiplication = [A[i] * B[i] for i in range(len(A))]

end = time.time()

print(f"Time taken: {end - start} ")



Time taken: 0.1547391414642334 


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [91]:
import numpy as np
import time

A = np.arange(1, 1000001)
B = np.arange(1, 1000001)

start = time.time()

multiplication = A * B

end = time.time()

print(f"Time taken: {end - start}")

Time taken: 0.004776477813720703


Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [92]:
import time

A = [i for i in range(1, 1000001)]
B = [i for i in range(1, 1000001)]

start = time.time()

dot = sum(A[i] * B[i] for i in range(len(A)))

end = time.time()

print(f"Time taken : {end - start} ")

Time taken : 0.14442849159240723 


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time

A = np.arange(1, 1000001)
B = np.arange(1, 1000001)

start = time.time()

dot = np.dot(A, B)

end = time.time()

print(f"Time taken: {end - start} ")

Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

In [ ]:
import time

A = [[i + j for j in range(1000)] for i in range(1000)]
B = [[i - j for j in range(1000)] for i in range(1000)]

start = time.time()

dot_ = [[sum(A[i][k] * B[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]

end = time.time()

print(f"Time taken: {end - start}")

Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [93]:
import numpy as np
import time

A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

start = time.time()

dot = np.dot(A, B)

end = time.time()

print(f"Time taken: {end - start} ")

Time taken: 0.06468081474304199 
